export {crearDeck} from './create-deck.js'
export {pedirCarta} from './pedir-carta.js'
export {valorCarta} from './valueCard.js'
export {turnoComputadora} from './turno-computadora.js'
export {crearCarta} from './crear-carta-html'